### ISSUE TITLE
Munge rule for \\ no longer accepted

### ISSUE THREAD

**Issue by marcuscooke** [PackeTsar/radiuid#38]
Hi John,

When attempting to create a munge rule to match the \\ using the example on the radiuid website the following error occurs however if i specify the partial domain first, for example "CEQ\\\\" this is accepted.

Here is the output:

administrator@radiuid:~/radiuid$ sudo radiuid set munge 101.0 match "\\\\" partial​

Unrecognized return criterion

A rule's match return criterion activates a rule either when the regex pattern match is COMPLETE or PARTIAL

###### Acceptable match criteria: ######

 - set munge 101.0 match \\ (complete | partial)

**Comment by marcuscooke** [comment]
please note that in the command there are definitely 4 slashes, not 2. not sure why they are being removed when type 4 in to this box

**Comment by marcuscooke** [comment]
to rule out an issue copying from Notepad++ i switched to regular notepad and got a different error starting from the second line (the initial line with \\\\ was accepted). No other rules seem to have the issue.

```
administrator@radiuid:~/radiuid$ sudo radiuid set munge 104.10 set-variable domain from-string "ceq"​
2018-04-30 16:17:58:   ##### COMMAND 'set munge 104.10 set-variable domain from-string ceq​' ISSUED FROM CLI BY USER 'root' #####

########################## EXECUTING COMMAND: set munge 104.10 set-variable domain from-string ceq​ ##########################
################################################################################################################################


Traceback (most recent call last):
  File "/bin/radiuid", line 4875, in <module>
    cli.interpreter()
  File "/bin/radiuid", line 3986, in interpreter
    self.filemgmt.save_config()
  File "/bin/radiuid", line 1002, in save_config
    self.newconfig = self.configcomment + "\n" + self.formatxml(ElementTree.tostring(self.root))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3: ordinal not in range(128)
administrator@radiuid:~/radiuid$ sudo radiuid set munge 104.20 set-variable user from-match "[a-zA-Z0-9]+$"​
2018-04-30 16:17:58:   ##### COMMAND 'set munge 104.20 set-variable user from-match [a-za-z0-9]+$​' ISSUED FROM CLI BY USER 'root' #####

########################## EXECUTING COMMAND: set munge 104.20 set-variable user from-match [a-za-z0-9]+$​ ##########################
#######################################################################################################################################


Traceback (most recent call last):
  File "/bin/radiuid", line 4875, in <module>
    cli.interpreter()
  File "/bin/radiuid", line 3986, in interpreter
    self.filemgmt.save_config()
  File "/bin/radiuid", line 1002, in save_config
    self.newconfig = self.configcomment + "\n" + self.formatxml(ElementTree.tostring(self.root))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 13: ordinal not in range(128)
administrator@radiuid:~/radiuid$ sudo radiuid set munge 104.30 set-variable slash from-string "\\"​
2018-04-30 16:17:58:   ##### COMMAND 'set munge 104.30 set-variable slash from-string \​' ISSUED FROM CLI BY USER 'root' #####

########################## EXECUTING COMMAND: set munge 104.30 set-variable slash from-string \​ ##########################
#############################################################################################################################


Traceback (most recent call last):
  File "/bin/radiuid", line 4875, in <module>
    cli.interpreter()
  File "/bin/radiuid", line 3986, in interpreter
    self.filemgmt.save_config()
  File "/bin/radiuid", line 1002, in save_config
    self.newconfig = self.configcomment + "\n" + self.formatxml(ElementTree.tostring(self.root))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1: ordinal not in range(128)
administrator@radiuid:~/radiuid$ sudo radiuid set munge 104.40 assemble domain slash user​
2018-04-30 16:17:58:   ##### COMMAND 'set munge 104.40 assemble domain slash user​' ISSUED FROM CLI BY USER 'root' #####

########################## EXECUTING COMMAND: set munge 104.40 assemble domain slash user​ ##########################
#######################################################################################################################


Traceback (most recent call last):
  File "/bin/radiuid", line 4875, in <module>
    cli.interpreter()
  File "/bin/radiuid", line 3986, in interpreter
    self.filemgmt.save_config()
  File "/bin/radiuid", line 1002, in save_config
    self.newconfig = self.configcomment + "\n" + self.formatxml(ElementTree.tostring(self.root))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 937, in _serialize_xml
    write(_escape_cdata(text, encoding))
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4: ordinal not in range(128)
```

**Comment by PackeTsar** [comment]
Marcus, your commands have some weird unicode characters in them. I just grabbed your failing commands from here in the issue and compared the characters to ones I typed out manually. Something weird is being added in there. Have a look

```
>>> b[0]
'sudo radiuid set munge 104.20 set-variable user from-match "[a-zA-Z0-9]+$"\xe2\x80\x8b'
>>> b[1]
'sudo radiuid set munge 104.20 set-variable user from-match "[a-zA-Z0-9]+$"'
```

**Comment by marcuscooke** [comment]
very strange.

i am copying the commands directly from your page in to notepad and
notepad++, editing them and then pasting them  (both with the same result)

manually typing them does seem to fix it.
