### ISSUE TITLE
v2.5.0 Freeradiuis Client File Issue

### ISSUE THREAD

**Issue by marcuscooke** [PackeTsar/radiuid#40]
Hi John,

I just thought I would let you know that there appears to be a problem with the 2.5.0 installation script.

Initially I tried installing it on Ubuntu 18 LTS and this was unable to create the clients.conf file (it produced an error).

I then went back to Ubuntu 16 LTS and it created the file without an issue but the subnets I added in the installation wizard never made it in to the configuration. I later added them with
>  sudo radius set clients ipv4 x.x.x.x password

This seemed to save them in the clients.conf however freeradius still will not accept radius accounting packets from any of the sources we added (we can now see them with the show clients table/file command).

Has anyone else had any issues with v2.5.0? Is there a way I can install an older version for comparison?

Kind regards,
Marcus Cooke

**Comment by marcuscooke** [comment]
hey mate, i hope you are well.

FYI
I cloned radiuid and instead checked out v2.4.3 and ran the installation and everything worked smoothly.

Regards,
Marcus

**Comment by marcuscooke** [comment]
Today I downgraded the initial deployment i had troubles with from v2.5.0 to v2.4.3 and it also worked.

**Comment by PackeTsar** [comment]
Can you produce the output where you are seeing issues for 2.5.0?

**Comment by marcuscooke** [comment]
I finally have this for you:

#####About to append the below client data to the FreeRADIUS client.conf
file#####
##################################################################################

client 10.0.0.0/8 {
    secret      = r4d1u1d
    shortname   = Created_By_RadiUID
 }

----- OK to write to client.conf file? [yes or no]:yes
###############Writing the above to the FreeRADIUS client.conf
file###############
##################################################################################


Writing:     [==================================================]

Traceback (most recent call last):
  File "radiuid.py", line 4957, in <module>
    cli.interpreter()
  File "radiuid.py", line 3219, in interpreter
    self.imu.im_utility()
  File "radiuid.py", line 3104, in im_utility
    self.imum.freeradius_editor(freeradiusedits)
  File "radiuid.py", line 2814, in freeradius_editor
    self.filemgmt.freeradius_client_editor("append", newclients)
  File "radiuid.py", line 1150, in freeradius_client_editor
    if entry["Family"] == "ipv4":
KeyError: 'Family'

**Comment by marcuscooke** [comment]
It turns out that this same issue also happens on Ubuntu 16 LTS if you use apt-get to upgrade all of the packages _before_ you install radiuid... This is a new behaviour as previously 16 LTS was fine.

**Comment by marcuscooke** [comment]
Actually this issue now happens on a completely unpatched Ubuntu 16 LTS box. It appears that the changes to freeradius in Ubuntu 18 LTS have filtered back down the freeradius package that comes with Ubuntu 16 LTS when you install RadiUID.

This means that no new RadiUID deployments can be done until this bug is fixed.
